version: '3.8'

services:
  postgres:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: sined-db-c
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - sined-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sined
      POSTGRES_PASSWORD: sinedpass
      POSTGRES_DB: sined

  pgadmin:
    image: dpage/pgadmin4
    container_name: sined-pgadmin-c
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - sined-network
    ports:
      - "8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: gabrielcoelho@inovadata.tech
      PGADMIN_DEFAULT_PASSWORD: sinedpass

networks:
  sined-network:
    name: sined-network
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data: