version: '3.8'

services:
  postgres:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: sined-db-c
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - sined-network
    ports:
      - "8080:5432"
    environment:
      POSTGRES_USER: sined
      POSTGRES_PASSWORD: sinedpass
      POSTGRES_DB: sined

networks:
  sined-network:
    name: sined-network
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data: